// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuInfoMeta } from "./MenuInfoMeta";

export interface MenuInfo { path: string, name: string, component: string, redirect: string | null, meta: MenuInfoMeta, children: Array<MenuInfo> | null, }