// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MenuMeta { title: string, icon: string | null, isHide: boolean | null, isKeepAlive: boolean | null, isAffix: boolean | null, isLink: string | null, isIframe: boolean | null, }