// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MenuMeta { title: string, icon: string, isHide: boolean, isKeepAlive: boolean, isAffix: boolean, link: string, isIframe: boolean, roles: Array<string>, }