// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuMeta } from "./MenuMeta";

export interface MenuCreateRequest { parent_id: number | null, menuType: string | null, name: string | null, componentAlias: string | null, isLink: boolean | null, path: string | null, redirect: string | null, btnPower: string | null, menuSort: number | null, meta: MenuMeta, }